version: '3'
services:
  logmaster:
    image: node:latest
    container_name: LogMaster
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_NO_WARNINGS=1