name: Intégration
run-name: Testing out GitHub Actions 🚀

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Starting pipeline
      run: echo "Pipeline started at $(date)"

    - name: Install dependencies
      run: npm install
    
    #- name: Typecheck
    #  run: npm run type-check

    #- name: Formatting Lint
    #  run: npm run lint

    - name: Formatting Prettier
      run: npm run prettier

    - name: Test
      run: npm test

    - name: Build
      run: npm run build

    - name: Ending pipeline
      run: echo "Pipeline ended at $(date)"